CREATE DATABASE BDGUFOS
USE BDGUFOS

CREATE TABLE CATEGORIA(
	CATEGORIA_ID INT PRIMARY KEY IDENTITY,
	TITULO VARCHAR(50) NOT NULL
)
CREATE TABLE LOCALIZACAO(
	LOCALIZACAO_ID INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	RAZAO_SOCIAL VARCHAR(70) NOT NULL,
	ENDERECO VARCHAR(100)
)
CREATE TABLE TIPO_USUARIO(
	TIPO_USUARIO_ID INT PRIMARY KEY IDENTITY,
	TITULO VARCHAR(255) NOT NULL
)
CREATE TABLE USUARIO(
	USUARIO_ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	TIPO_USUARIO_ID INT FOREIGN KEY REFERENCES TIPO_USUARIO(TIPO_USUARIO_ID)
)
CREATE TABLE EVENTO(
	EVENTO_ID INT PRIMARY KEY IDENTITY,
	TITULO VARCHAR(50) NOT NULL,
	DATA_EVENTO DATETIME NOT NULL,
	ACESSO_LIVRE BIT DEFAULT(1) NOT NULL,
	CATEGORIA_ID INT FOREIGN KEY REFERENCES CATEGORIA(CATEGORIA_ID),
	LOCALIZACAO_ID INT FOREIGN KEY REFERENCES LOCALIZACAO(LOCALIZACAO_ID)
)
CREATE TABLE PRESENCA(
	PRESENCA_ID INT PRIMARY KEY IDENTITY,
	STATUS_PRESENCA BIT DEFAULT(1) NOT NULL,
	USUARIO_ID INT FOREIGN KEY REFERENCES USUARIO(USUARIO_ID),
	EVENTO_ID INT FOREIGN KEY REFERENCES EVENTO(EVENTO_ID)
)

--TROCAR CAMPO STATUS 
