USE BDGUFOS

INSERT INTO CATEGORIA(TITULO) VALUES  ('TECNOLOGIA'), ('GASTRONOMIA'), ('MEETUP')

INSERT INTO LOCALIZACAO(CNPJ, RAZAO_SOCIAL, ENDERECO) VALUES ('03774819008189', 'SENAI-INFORMÁTICA', 'Al. Barão de Limeira, 539 - Santa Cecília - São Paulo')

INSERT INTO TIPO_USUARIO(TITULO) VALUES ('ADMINISTRADOR'), ('ALUNO')

INSERT INTO USUARIO(NOME, EMAIL, SENHA, TIPO_USUARIO_ID) VALUES ('ADMINISTRADOR', 'ADM@GMAIL.COM', '123',1)
INSERT INTO USUARIO(NOME, EMAIL, SENHA, TIPO_USUARIO_ID) VALUES ('ARIEL PAIXAO', 'GATINHO123@GMAIL.COM', 'LASANHA',2)

INSERT INTO EVENTO(TITULO, DATA_EVENTO, ACESSO_LIVRE, CATEGORIA_ID, LOCALIZACAO_ID) VALUES ('C#', '2019-08-07T18:00:00', 0, 2,4), ('SEMANTICA', GETDATE(),1,3,4)

INSERT INTO PRESENCA(STATUS_PRESENCA, USUARIO_ID, EVENTO_ID) VALUES (1, 2, 'AGUARDANDO'), (1, 1, 'CONFIRMADO')
